<?php
$homeUrl = $this->url('home',array(),array('force_canonical' => true));
?>
<section class="invoice">
          <!-- title row -->
          <div class="row">
            <div class="col-md-12 col-sm-12 col-xs-12">
              <h2 class="page-header">
                 SO#<?php echo $salesorderData['_id'];?> - <?php echo $salesorderData['customer']?>
                <small class="pull-right" style="padding-left:5em"><?php echo Date('m/d/Y', $salesorderData['created']->sec);?></small>
              </h2>
            </div><!-- /.col -->
          </div>
          <!-- info row -->

          <div class="row invoice-info">
 <!--            <div class="col-sm-4 invoice-col">
              From
              <address>
                 Raz Philippines, Inc.</strong><br>
              </address>
            </div><!-- /.col -->
            <div class="col-md-4 col-sm-4 col-xs-12 invoice-col">
              Customer:
              <br/>
              <address>
                <strong>Name:</strong> <?php echo $salesorderData['customer']?><br>
                <strong>Phone:</strong> <?php echo $salesorderData['phone']?><br>
                <strong>Address:</strong> <?php echo $salesorderData['deliveryAddr']?><br>
              </address>
            </div><!-- /.col -->


            <div class="col-md-4 col-sm-4 col-xs-12 invoice-col">
              Payment:
              <address>
              <b>Payment via:</b> <?php echo $salesorderData['paymentType']?><br>
              <b>Paid:</b> <?php echo ($salesorderData['paid'] === TRUE)? Date('M d Y ', $salesorderData['paid_date']->sec) : 'Unpaid' ?> <br>
              <b>Seller:</b> <?php echo $salesorderData['seller'];?> <br>
              </address>
            </div><!-- /.col -->

            <div class="col-md-4 col-sm-4 col-xs-12 invoice-col">
              Delivery:
              <br/>
              <address>
              <b>Type:</b> <?php echo $salesorderData['deliveryType']?><br>
                <strong>Date:</strong> <?php echo Date('M/d/Y', $salesorderData['shipmentDate']->sec)?> -
                        <?php echo $salesorderData['deliveryTime']?>
                      <br>
              <b>Delivered:</b> <?php echo ($salesorderData['shipped'] === TRUE)? Date('M d Y ', $salesorderData['shipped_date']->sec) : 'Not yet' ?> <br>
              <b>Rider:</b> <?php echo $salesorderData['rider']; ?> <br>
              </address>
            </div><!-- /.col -->

          </div><!-- /.row -->

          <!-- Table row -->
          <div class="row">
            <div class="col-md-12 col-sm-12 col-xs-12 table-responsive">
              <table class="table table-striped">
                <thead>
                  <tr>
                    <th>Qty</th>
                    <th>Product</th>
                    <th>Price</th>
                    <th>Discount</th>
                    <th>Subtotal</th>
                  </tr>
                </thead>
                <tbody>
                <?php foreach($salesorderData['items'] as $item){?>
                  <tr>
                    <td><?php echo $item['qty']?></td>
                    <td><?php echo $item['sku']?></td>
                    <td><?php echo number_format($item['price'],2)?></td>
                    <td><?php echo number_format($item['discount'],2)?></td>
                    <td><?php echo number_format($item['subtotal'],2)?></td>
                  </tr>
                <?php }?>
                </tbody>
              </table>

            </div><!-- /.col -->
            <div>

            </div>
          </div><!-- /.row -->

          <div class="row">
            <!-- accepted payments column -->
            <div class="col-md-6 col-sm-6 col-xs-12">


                <div class="form-group">

                    <label for="itemname">Shipping/Delivery Fee:</label>
                    <div>
                    <?php if(!empty($salesorderData['shippingfee'])):?>
                        &#8369;  <?php echo number_format($salesorderData['shippingfee'],2);?>
                    <?php else:?>
                        &#8369;  0.00
                    <?php endif; ?>
                    </div>

                </div>

                Notes:
                <pre class="text-muted well well-sm no-shadow" style="font-style:italic; font-size:.9em; font-family: 'Helvetica Neue',Helvetica,Arial,sans-serif;" ><?php echo $salesorderData['note'];?></pre>
            </div><!-- /.col -->
            <div class="col-md-6 col-sm-6 col-xs-12">
              <!-- <p class="lead">Amount Due 2/22/2014</p> -->
              <div class="table-responsive">
                <table class="table">
                  <tbody>
                  <tr>
                    <th>Total:</th>
                    <td>&#8369; <?php echo number_format($salesorderData['total'],2)?></td>
                  </tr>
                  <tr>
                    <th>Paid Total:</th>
                    <td>&#8369; <?php echo number_format($salesorderData['total'] - $salesorderData['payment_left'],2)?></td>
                  </tr>
                  <?php if($salesorderData['payment_left'] > 0 ):?>
                  <tr>
                    <th>Accounts Receivable:</th>
                    <td>&#8369; <?php echo number_format($salesorderData['payment_left'],2)?> </strong></td>
                  </tr>
                  <?php endif;?>
                </tbody></table>

                <!-- PAYMENTS -->
                <div id="paymentsmade" class="table-responsive">
                    Payment Breakdown:
                  <?php if(count($salesorderData['payments'] > 0)):?>

                    <table class="table table-condensed" >

                        <tbody>
                        <?php
                          foreach($salesorderData['payments'] as $payment):
                          if($payment['amount'] > 0):
                          ?>
                          <tr>
                            <td style="text-align:left">
                              <?php echo Date('M d, Y',$payment['paid']->sec);?>
                            </td>
                            <td>&#8369; <?php echo number_format($payment['amount'],2)?></td>

                          </tr>

                        <?php
                          endif;
                          endforeach;
                        ?>
                      </tbody>
                    </table>
                  <?php endif;?>

                </div>
                <!-- PAYMENTS -->
              </div>
            </div><!-- /.col -->
          </div><!-- /.row -->
          <div class="row">
            <div class="col-sm-12">
              <span class=" pull-right">
              Performax 
              </span>
            </div>
          </div>
          <!-- this row will not appear when printing -->
          <div class="row no-print hideOnPrint">
            <div class="col-xs-12">

              <a href="?print=true" target="_blank" class="btn btn-default"><i class="fa fa-print"></i> Print</a>

              <?php if(!$salesorderData['finalized']){ ?>
                <a href="<?php echo $homeUrl;?>salesorder/edit/<?php echo $salesorderData['_id']?>" class="btn btn-primary"><i class="fa fa-pencil"></i> Edit</a>
              <?php }?>

              <?php if(!$salesorderData['finalized']){ ?>
                <a href="#finalizemodal" data-toggle="modal">
                   <button class="btn btn-success pull-right" style="margin-left: 5px;">
                   <i class="fa fa-thumbs-up"></i>
                    Finalize Invoice</button>
                </a>
              <?php }?>

              <?php if ($salesorderData['finalized'] && !$salesorderData['shipped']) {?>
                <!-- <a href="<?php echo $homeUrl;?>salesorder/markasdelivered/<?php echo $salesorderData['_id']?>"> -->
                <a href="#deliveredmodal" data-toggle="modal">
                   <button class="btn btn-primary pull-right" style="margin-left: 5px;">
                   <i class="fa fa-truck"></i>
                    Mark as Delivered</button>
                </a>
              <?php } ?>



              <?php if ($salesorderData['finalized'] && !$salesorderData['paid']) {?>
              <a href="#paymentmodal" data-toggle="modal">
                 <button class="btn btn-success pull-right" style="margin-left: 5px;">
                 <i class="fa fa-credit-card"></i>
                  Create Payment</button>
              </a>
              <?php }?>

            </div>





            <div id="deliveredmodal" class="modal fade">
              <div class="modal-dialog">
                <div class="modal-content">
                  <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span></button>
                    <h4 class="modal-title">Mark as Delivered </h4>
                  </div>
                  <div class="modal-body">
                    <p>This will Decrement stock, Are you sure?</p>
                  </div>
                  <div class="modal-footer">
                    <button type="button" class="btn btn-default pull-left" data-dismiss="modal">Close</button>
                    <a  href="<?php echo $homeUrl;?>salesorder/markasdelivered/<?php echo $salesorderData['_id']?>">
                        <button type="button" class="btn btn-success">
                            <i class="fa fa-thumbs-up"></i> Decrement stock
                        </button>
                    </a>
                  </div>
                </div><!-- /.modal-content -->
              </div><!-- /.modal-dialog -->
            </div><!-- /.modal -->


            <div id="paymentmodal" class="modal fade">
              <div class="modal-dialog">
                <div class="modal-content">
                  <form method="POST" role="form" action="<?php echo $homeUrl;?>salesorder/payments/<?php echo $salesorderData['_id']?>" onSubmit="validate(this, event)">

                  <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span></button>
                    <h4 class="modal-title">Create Payment</h4>
                  </div>
                  <div class="modal-body">

                            <div class="form-group">
                                <div class="input-group">
                                    <div class="input-group-addon">
                                    &#8369;
                                    </div>
                                    <input onKeyUp="validatePayment()" id="payment" name="paymenttobemade" type="text" class="form-control" placeholder="payment" value="<?php echo number_format((float)$salesorderData['payment_left'],2,'.','')?>">
                                </div><!-- /.input group -->
                            </div>

                  </div>
                  <div class="modal-footer">
                    <button type="button" class="btn btn-default pull-left" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-success">Save Payment</button>
                  </div>
                  </form>
                </div><!-- /.modal-content -->
              </div><!-- /.modal-dialog -->
            </div><!-- /.modal -->


            <div id="finalizemodal" class="modal fade">
              <div class="modal-dialog">
                <div class="modal-content">
                  <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span></button>
                    <h4 class="modal-title">Finalize Invoice</h4>
                  </div>
                  <div class="modal-body">
                    <p>You cannot edit once you finalize this invoice</p>
                  </div>
                  <div class="modal-footer">
                    <button type="button" class="btn btn-default pull-left" data-dismiss="modal">Close</button>
                    <a href="<?php echo $homeUrl;?>salesorder/finalize/<?php echo $salesorderData['_id']?>">
                        <button type="button" class="btn btn-success">
                            <i class="fa fa-thumbs-up"></i> Finalize Invoice
                        </button>
                    </a>
                  </div>
                </div><!-- /.modal-content -->
              </div><!-- /.modal-dialog -->
            </div><!-- /.modal -->

          </div>
        </section>
        <script src="<?php echo $homeUrl;?>js/plugins/datepicker/bootstrap-datepicker.js" type="text/javascript"></script>

        <script type="text/javascript">


            function validatePayment()
            {

                paymentElement = document.getElementById('payment');
                paymentElement.value = paymentElement.value.replace(/[^\d.-]/g, '')
                console.log(paymentElement.value);
                if((paymentElement.value == "." )|| (paymentElement.value == "0..")){
                    paymentElement.value = "0."
                }


                if(paymentElement.value >= <?php echo $salesorderData['payment_left']?>){
                    paymentElement.value = <?php echo $salesorderData['payment_left'];?>
                }
            }


        </script>
