<?php

$homeUrl = $this->url('home',array(),array('force_canonical' => true));
function determineSortByLink($getParam, $sortName){

    if(isset($getParam['sort']) && $getParam['sort'] == $sortName){
        if(isset($getParam['order']) && $getParam['order'] == 'DESC'){
            $getParam['order'] = 'ASC';
        }else{
            $getParam['order'] = 'DESC';
        }
    }else{
        $getParam['sort'] = $sortName;
    }

    return http_build_query($getParam);
}

function generatePagination($getParam, $pagination, $homeUrl)
{
   
    $html = '<div class="row"><div class="col-sm-12">
            <div class="btn-group pull-right"> Pages: ';
    $homeUrl .= "product/list";

    $currentPage = 1;
    if(isset($getParam['page']) && $getParam['page'] > 0){
        $currentPage = $getParam['page'];
    }
    $maxCount = count($pagination);
    $tmpGet = $getParam;
    foreach ($pagination as $key => $page) {
        if($page == 0 ) continue;
        $getParam['page'] = $page;
        $getQuery = http_build_query($getParam);

        $class = "btn-default";
        if($currentPage == $page)
            $class = "btn-primary";
        $html .= "<a style='padding-right:3px' href='{$homeUrl}?{$getQuery}'>";
        $html .= "<button class='btn {$class} btn-sm'>{$page}</button></a>";
    }
    $html .= '</div><!-- /.btn-group --></div></div>';
    return $html;
}
    
?>
<div class="box box-default">

<div class="box-body">



    <div class="row">



        <div class="col-sm-6">
            <a class="pull-left" href="<?php echo $this->basePath();?>/product/add-product"> <button type="button" id="add-variant-btn" class="btn btn-primary btn-sm">Add Product</button> </a>
        </div>
        <div class="col-sm-6">
        <form action="<?php echo $this->basePath();?>/product/list" method="GET">
            <div class="input-group">

                <input type="text" name="q" class="form-control input-sm pull-right" style="width: 150px;" placeholder="Search"
                  value="<?php if(isset($getParam['q'])) echo htmlspecialchars($getParam['q']);?>">
                <div class="input-group-btn">
                    <button type="submit" class="btn btn-sm btn-default"><i class="fa fa-search"></i></button>
                </div>
            </div>
            </form>
        </div>
    </div>



    <div class="row">


            <div class="box-body table-responsive col-sm-12">
                <table class="table table-hover table-striped table-bordered">
                    <tbody><tr>
                        <th>
                            <a href="<?php echo $this->basePath();?>/product/list?<?php echo determineSortByLink($getParam, 'itemname');?>">
                            Item Name (
                            <?php
                            $totalProducts = $data->count();
                            echo $totalProducts; echo ($totalProducts == 1)? " item": " items" ?>)</a>
                        </th>
                        <th>
                            <a href="<?php echo $this->basePath();?>/product/list?<?php echo determineSortByLink($getParam, 'active');?>">
                            Active </a>
                        </th>
                        <th>&nbsp;</th>
                    </tr>
                    <?php 
                    if(count($data) > 0 )
                    {
                        foreach($data as $product){ ?>
                    <tr>
                        <td>
                            <a href="<?php echo $this->basePath();?>/product/details?product_id=<?php echo $product['_id']?>">
                                    <?php if (isset($product['itemname'])) { echo $product['itemname']; }?>
                            </a>
                        </td>
                        <td>
                            <?php if (isset($product['active']) && $product == TRUE) 
                            {
                                echo '<small class="badge bg-green">Active</small>';
                            } else {
                                echo '<small class="badge bg-gray">Disabled</small>';
                            }?>
                        </td>
                        <td id="accordion-option-<?php echo $product['_id']?>">
                            <a href="<?php echo $this->basePath();?>/product/details?product_id=<?php echo $product['_id']?>">
                                <button class="btn btn-primary btn-xs">
                                    Details
                                </button>
                            </a><!-- 
                            <a style="padding-left:2em" data-toggle="collapse" data-parent="#accordion-option-<?php echo $product['_id']?>"
                            href="#accordion-<?php echo $product['_id']?>">
                                <button class="btn btn-danger btn-xs">
                                Delete
                                </button>
                            </a>
                            <div id="accordion-<?php echo $product['_id']?>" class="collapse" style="height:0px">
                                <div class="box-body">
                                <a href="<?php echo $this->basePath();?>/product/delete?product_id=<?php echo $product['_id']?>">
                                    <button class="btn btn-danger btn-xs">
                                    Confirm Delete
                                    </button>
                                </a>
                                <a data-toggle="collapse" data-parent="#accordion-option-<?php echo $product['_id']?>"
                                   href="#accordion-<?php echo $product['_id']?>">
                                    <button class="btn btn-xs">Cancel</button>
                                </a>
                                </div>
                            </div> -->
                        </td>
                    </tr>
                   <?php }}?>
                </tbody></table>
            </div>

           

        </div>

 <?php echo generatePagination($getParam, $pagination, $homeUrl);?>

</div><!-- /.box-body -->
</div>
