<?php
$homeUrl = $this->url('home',array(),array('force_canonical' => true));
?>
<style>
    .sales-order-form{
 /*       height: 100%;*/
        width: 100%;
    }
    .no-border{
        border: 0px;
    }

.order-detail-title{
    width: 200px;
    min-width: 50px;
}
.order-detail-value{

}

.tt-query, /* UPDATE: newer versions use tt-input instead of tt-query */
.tt-hint {
    width: 396px;
    height: 30px;
    padding: 8px 12px;
    font-size: 24px;
    line-height: 30px;
    border: 2px solid #ccc;
    border-radius: 8px;
    outline: none;
}

.tt-query { /* UPDATE: newer versions use tt-input instead of tt-query */
    box-shadow: inset 0 1px 1px rgba(0, 0, 0, 0.075);
}

.tt-hint {
    color: #999
}

.tt-dropdown-menu {
    width: 422px;
    margin-top: 12px;
    padding: 8px 0;
    background-color: #fff;
    border: 1px solid #ccc;
    border: 1px solid rgba(0, 0, 0, 0.2);
    border-radius: 8px;
    box-shadow: 0 5px 10px rgba(0,0,0,.2);
}

.tt-suggestion {
    padding: 3px 20px;
    font-size: 18px;
    line-height: 24px;
}

.tt-suggestion.tt-is-under-cursor { /* UPDATE: newer versions use .tt-suggestion.tt-cursor */
    color: #fff;
    background-color: #0097cf;

}
</style>

<div class="box box-default">

<div class="box-body">
<form method="POST" role="form" action="<?php echo $homeUrl;?>purchaseorder/new" onSubmit="validate(this, event)">
<section class="content">    
        <div class="row">
            
            <div class="col-xs-6">
                <div class="form-group">
                        <div>
                            Reason:
                        </div>
                        <div class="input-group">
                            <select name="reason" class="form-control input-sm">
                                <option value="Returns">Returns</option>
                                <option value="Adjustments">Adjustments </option>
                                <option value="Defective"> Defective </option>
                            </select>
                        </div>
                </div>


            </div>
            


            <div class="col-xs-6">
                    
                <div class="form-group">
                    <div class="input-group">
                        <div class="input-group-addon">
                            <i class="fa fa-calendar"></i>
                        </div>
                        <input id="dateAdjusted" name="dateAdjusted" type="text" placeholder="Date" class="form-control input-sm" data-inputmask="'alias': 'mm/dd/yyyy'" data-mask="">
                    </div><!-- /.input group -->
                </div>
            </div>
        </div>
        <div>&nbsp;</div>

        <!-- Table row -->
        <div class="row">
            <div class="col-12">
                <div class="input-group">
                    <input id="typeaheadsearch" type="text" name="q" class="form-control" placeholder="Search Products">
                </div>
            </div>
        </div>
        <div class="row">

            <div class="col-12 table-responsive">
                <table class="table table-bordered">
                    <thead>
                        <tr>
                            
                            <th width="35%">SKU</th>
                            <th width="12%">Qty</th>
                            <th width="10%">Current Stock</th>
                            <th width="10%">After Adjusted Stock</th>
                            <th width="1%">&nbsp;</th>
                        </tr>
                    </thead>
                    <tbody id="order_tbody">



                    </tbody>
                </table>
            </div><!-- /.col -->
        </div><!-- /.row -->
        <div class="row">
            <!-- accepted payments column -->
            <div class="col-xs-6">
                <div class="form-group">
                    <div>Note:</div>
                    <textarea class="form-control" name="note"> </textarea>
                </div>
            </div>
            <div class="col-xs-6">
               <div class="table-responsive">
                    <table class="table">
                        <tbody>
                        <tr>
                            <td><span id="total-units">0</span> Units</td>
                        </tr>
                        <tr>
                            <td><strong>&#8369; <span id="total-cost">0.00</span>
                            </strong></td>
                        </tr>
                    </tbody></table>
                </div>
            </div>
            
        </div>    
        <div class="row">
            <!-- accepted payments column -->
            <div class="form-group">
                <button type="submit" id="add-variant-btn" class="btn btn-primary">Place Order</button>
            </div>
            
        </div>
</section>
</form>
</div>
</div>


<div class="modal modal-danger fade add-variant-modal" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
    <div class="modal-dialog ">
    <div class="modal-content">

        <div class="modal-header">
            <button type="button" class="close btn-sm" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <h4 class="modal-title">Invoice has missing fields</h4>
        </div>
        <div class="modal-body">
            <ul id="modalul">
            </ul>
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-outline pull-left" data-dismiss="modal">Close</button>
        </div>
    </div>
    </div>
</div>

<link href="<?php echo $homeUrl;?>js/plugins/timepicker/bootstrap-timepicker.min.css" rel="stylesheet"/>
<script src="<?php echo $homeUrl;?>js/plugins/typeahead.js" type="text/javascript"/></script>
<script src="<?php echo $homeUrl;?>js/plugins/input-mask/jquery.inputmask.js" type="text/javascript"></script>
<script src="<?php echo $homeUrl;?>js/plugins/input-mask/jquery.inputmask.date.extensions.js" type="text/javascript"></script>
<script src="<?php echo $homeUrl;?>js/plugins/input-mask/jquery.inputmask.extensions.js" type="text/javascript"></script>
<script src="<?php echo $homeUrl;?>js/plugins/timepicker/bootstrap-timepicker.js" type="text/javascript"></script>

<script type="text/javascript">

function removeRow(event, trname)
{
    document.getElementById(trname).remove();
    event.preventDefault();
    updateTotalandTotalUnits();
    clearTypeAhead();
}

function clearTypeAhead()
{
    typeahead = document.getElementById("typeaheadsearch");
    typeahead.value = '';
}

function computeAfterStock(itemCounter)
{


    afterAdjustStock = "item-"+ itemCounter +"-afterAdjustStock"
    availableStock = "item-"+ itemCounter +"-available"
    qtyId = "item-"+ itemCounter +"-qty";


    qtyElement = document.getElementById(qtyId);
    afterAdjustStockElement = document.getElementById(afterAdjustStock);
    availableStockElement = document.getElementById(availableStock);

    qtyElement.value = qtyElement.value.replace(/[^\d-]/g, '')


    if((qtyElement.value == "." )|| (qtyElement.value == "0..")){
        qtyElement.value = "0"
    }



    afterAdjustStockValue = Math.floor( availableStockElement.value) + Math.floor( qtyElement.value);


    afterAdjustStockElement.value = afterAdjustStockValue;

    updateTotalandTotalUnits();
}


var formIncorrect = 0;
var formComplete = 0;
submitButtonClicked = 0;


function validate(form, event){
    submitButtonClicked = 1;
    var modalul =  document.getElementById("modalul");
    var textnode;
    formIncorrect = 0;
    while (modalul.firstChild) {
        modalul.removeChild(modalul.firstChild);
    }
    
    if( $('#supplier').val() == "")
    {
        formIncorrect = 1;
        supplierLi = document.createElement("li");
        textnode = document.createTextNode("Must have a Supplier");
        supplierLi.appendChild(textnode);
        modalul.appendChild(supplierLi);
    }

    totalUnits = Math.floor(document.getElementById('total-units').innerHTML);
    console.log(totalUnits);
    if( isNaN(totalUnits) == true ){
        formIncorrect = 1;
        supplierLi = document.createElement("li");
        textnode = document.createTextNode("Incorrect Value for qty");
        supplierLi.appendChild(textnode);
        modalul.appendChild(supplierLi); 
    }
    
    
    if( $('#dateAdjusted').val() == "")
    {
        formIncorrect = 1;
        dateAdjustedLi = document.createElement("li");
        textnode = document.createTextNode("Must have a Date");
        dateAdjustedLi.appendChild(textnode);
        modalul.appendChild(dateAdjustedLi);
    }
    
    if( $('.variant-item').length == 0){
        formIncorrect = 1;
        noitems = document.createElement("li");
        textnode = document.createTextNode("No Items in the Cart");
        noitems.appendChild(textnode);
        modalul.appendChild(noitems);
    }


    // alert(formIncorrect);
    // exit;
    if(formIncorrect == 1){
        
        $('.modal').modal('show');
        event.preventDefault();    
    }
    
    

}



function updateTotalandTotalUnits(){

    qtyelements = document.getElementsByClassName('qty-element');
    var x;
    var count = 0;
    for(x = 0; x < qtyelements.length; x++){
        // console.log(qtyelements[x].value);
        count = count + parseInt(qtyelements[x].value);
    }


    document.getElementById('total-units').innerHTML = count;

    subtotalelements = document.querySelectorAll('.subtotal-element');

    var total = 0;
    for(x = 0; x < subtotalelements.length; x++){
        total = total + parseFloat(subtotalelements[x].value);
    }


    total = total.toFixed(2).replace(/./g, function(c, i, a) {
        return i && c !== "." && ((a.length - i) % 3 === 0) ? ',' + c : c;
    });
    document.getElementById('total-cost').innerHTML = total;


}

var itemCounter = 0;

var skus = new Bloodhound({
    datumTokenizer: function (datum) {
        return Bloodhound.tokenizers.whitespace(datum.value);
    },
    queryTokenizer: Bloodhound.tokenizers.whitespace,
    remote: {
        url: '<?php echo $homeUrl;?>product/typeahead?q=%QUERY',
        filter: function (data) {
            // Map the remote source JSON array to a JavaScript object array
            return $.map(data, function (variant) {

                return { "value": variant.variant,
                         "sku"  : variant.sku,
                         "variant_id"  : variant._id.$id,
                         "stock"  : variant.stock,
                         "cost"  : variant.cost,

                };
            });
        }
    }
});

function createEntry(datum)
{

    input_variantName = document.createElement("input");
    input_variantName.setAttribute("type", "text");
    input_variantName.setAttribute("class", "variant-item form-control sales-order-form");
    input_variantName.setAttribute("name", "items["+ itemCounter +"][sku]");
    input_variantName.setAttribute("value", datum.value);
    input_variantName.setAttribute("id", "item-"+ itemCounter +"-sku");

    input_sku = document.createElement("input");
    input_sku.setAttribute("type", "hidden");
    input_sku.setAttribute("name", "items["+ itemCounter +"][id]");
    input_sku.setAttribute("class", "form-control sales-order-form");
    input_sku.setAttribute("value", datum.variant_id);
    input_sku.setAttribute("id", "item-"+ itemCounter +"-id");
    salesorder_td_1 = document.createElement("td");
    salesorder_td_1.appendChild(input_variantName);
    salesorder_td_1.appendChild(input_sku);
    
    input_qty = document.createElement("input");
    input_qty.setAttribute("type", "text");
    input_qty.setAttribute("name", "items["+ itemCounter +"][qty]");
    input_qty.setAttribute("value", 1);
    input_qty.setAttribute("class", "form-control sales-order-form qty-element");
    input_qty.setAttribute("id", "item-"+ itemCounter +"-qty");
    input_qty.setAttribute("onkeyup", "computeAfterStock("+ itemCounter +")");
    salesorder_td_2 = document.createElement("td");
    salesorder_td_2.appendChild(input_qty);


    input_available = document.createElement("input");
    input_available.setAttribute("type", "text");
    input_available.setAttribute("disabled", "disabled");
    input_available.setAttribute("class", "form-control sales-order-form");
    input_available.setAttribute("value", datum.stock);
    input_available.setAttribute("id", "item-"+ itemCounter +"-available");
    salesorder_td_3 = document.createElement("td");
    salesorder_td_3.appendChild(input_available);

    afterAdjustValue = datum.stock + 1;
    input_afterAdjustStock = document.createElement("input");
    input_afterAdjustStock.setAttribute("type", "text");
    input_afterAdjustStock.setAttribute("name", "items["+ itemCounter +"][afterAdjustStock]");
    input_afterAdjustStock.setAttribute("class", "form-control sales-order-form");
    input_afterAdjustStock.setAttribute("value", afterAdjustValue);
    input_afterAdjustStock.setAttribute("id", "item-"+ itemCounter +"-afterAdjustStock");
    input_afterAdjustStock.setAttribute("disabled", "disabled");
    input_afterAdjustStock.setAttribute("onkeyup", "computeAfterStock("+ itemCounter +")");
    salesorder_td_4 = document.createElement("td");
    salesorder_td_4.appendChild(input_afterAdjustStock);



    trname = "tr-item-"+ itemCounter;
    remove_link = document.createElement("a");
    remove_link.setAttribute("href","#");
    remove_link.setAttribute("onClick", "removeRow(event, '"+ trname +"')");
    remove_icon = document.createElement("i");
    remove_icon.setAttribute("class", "fa fa-trash-o");
    remove_link.appendChild(remove_icon);
    salesorder_td_5 = document.createElement("td");
    salesorder_td_5.appendChild(remove_link);


    table_tbody = document.getElementById("order_tbody");
    salesorder_tr = document.createElement("tr");
    salesorder_tr.setAttribute("id", trname);

    salesorder_tr.appendChild(salesorder_td_1);
    salesorder_tr.appendChild(salesorder_td_2);
    salesorder_tr.appendChild(salesorder_td_3);
    salesorder_tr.appendChild(salesorder_td_4);
    salesorder_tr.appendChild(salesorder_td_5);

    table_tbody.appendChild(salesorder_tr);


    itemCounter = itemCounter + 1;
    updateTotalandTotalUnits();
    clearTypeAhead();

}
var formmodified = 0
$(document).ready(function() {

    skus.initialize();

    $("form").change(function() {
        formmodified = 1;
    });

    window.onbeforeunload = confirmExit;
    function confirmExit() {
        if (formmodified == 1 && submitButtonClicked == 1) {
            return "Do you wish to leave the page?";
        }
    }

    // $("#datemask").inputmask("dd/mm/yyyy", {"placeholder": "dd/mm/yyyy"});
    $("[data-mask]").inputmask();
    $('#typeaheadsearch').typeahead(null, {
      name: 'skusearch',
      displayKey: 'value',
      source: skus.ttAdapter()
    }).bind("typeahead:selected", function(obj, datum, name) {
        console.log(obj, datum, name);
        createEntry(datum);
    });
    $(".timepicker").timepicker({showInputs: false,disableFocus: true, defaultTime:false});



});
</script>