<?php
    
    $rawValues = $variantData;
    $messages = NULL;


?>
<div class="row">
    <form style="pull-left" method="POST" action="<?php echo $this->basePath();?>/product/variant?variant_id=<?php echo htmlspecialchars($variantData['_id'])?>">
    <div class="col-md-12">

<?php


/// display input Filter

if(isset($inputFilter))
{


    $messages  = $inputFilter->getMessages();
    $rawValues = $inputFilter->getRawValues();

    $string = '<div class="alert alert-warning alert-dismissable">';
    $string .= '    <i class="fa fa-warning"></i>';
    $string .= '    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>';

    foreach($messages as $key => $errorMessages){               
            foreach($errorMessages as $message)
            $string .= '       <p><i class="fa fa-warning"></i> <strong>'. $key.': </strong> '.  $message.'</p>';
    }
    $string .= '</div>';
    echo $string;
}


?>
        <h4>Update Variant</h4>

            <?php if(isset($success) && $success == TRUE) { ?>
                <div class="alert alert-success alert-dismissable">
                    <i class="fa fa-check"></i>
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                    <b>Variant</b> Successfully Updated!
                </div>
            <?php }?>
        

        <div class="form-group">                 
            <label for="sku">SKU: </label>
            <input type="hidden" name="action" value="update">
            <input type="hidden" name="variant_id" value="<?php echo htmlspecialchars($variantData['_id'])?>">
            <input type="text" class="form-control" id="sku" name="sku" placeholder="SKU"
            value="<?php if(isset($rawValues['sku'])){ echo htmlspecialchars($rawValues['sku']); }?>">
            <input type="hidden" name="product_id" value="<?php echo htmlspecialchars($variantData['_id'])?>">
        </div>
        <div class="form-group">
            <label for="variant">Variant Name: </label>
            <input type="text" class="form-control" id="variant" name="variant" placeholder="Item Name"
            value="<?php if(isset($rawValues['variant'])){ echo htmlspecialchars($rawValues['variant']); }?>">
        </div>
        <div class="form-group">
            <label for="cost">Capital Price: </label>
            <input type="text" class="form-control" id="cost" name="cost" placeholder="Cost Price"
            value="<?php if(isset($rawValues['cost'])){ echo htmlspecialchars($rawValues['cost']); }?>">
        </div>
        <div class="form-group">
            <label for="price">Price (SRP): </label>
            <input type="text" class="form-control" id="price" name="price" placeholder="SRP"
            value="<?php if(isset($rawValues['price'])){ echo htmlspecialchars($rawValues['price']); }?>">
        </div>

    </div>


    <div class="form-group col-md-9">
        <button type="submit" id="add-variant-btn" class="btn btn-primary">Add Variant</button>
        <a href="<?php echo $this->basePath();?>/product/details?product_id=<?php echo $variantData['product_id'];?>">
            <button type="button" id="add-variant-btn" class="btn btn-default btn-sm">Cancel</button>
        </a>
    </div>
    </form>


    <form class="col-md-3" method="POST">
        <input type="hidden" name="action" value="delete">
        <input type="hidden" name="variant_id" value="<?php echo htmlspecialchars($variantData['_id'])?>">


            <button data-toggle="collapse" data-parent="#delete-accordion" href="#delete-accordion" type="submit" class="btn btn-default btn-sm"> 
                <i class="fa fa-trash-o"></i> Remove Variant
            </button>


            <div id="delete-accordion" class="collapse" style="height:0px">
                <div class="box-body">
                    <a href="<?php echo $this->basePath();?>/product/remove-variant?product_id=<?php echo $variantData['product_id'];?>&variant_id=<?php echo $variantData['_id'];?>">
                        <button type="button" class="btn btn-danger btn-xs">
                        Confirm Delete
                        </button>
                    </a>

                    <button data-toggle="collapse" data-parent="#delete-accordion" href="#delete-accordion"" class="btn btn-default btn-xs">Cancel
                    </button>
                </div>
            </div>
        
    </form>
</div>