<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'Backend\Module'                       => __DIR__ . '/Module.php',
  'Backend\Controller\ProductController' => __DIR__ . '/src/Backend/Controller/ProductController.php',
  'Backend\Controller\OrderController'   => __DIR__ . '/src/Backend/Controller/OrderController.php',
  'Backend\Controller\ProjectController'   => __DIR__ . '/src/Backend/Controller/ProjectController.php',
  'Backend\Controller\SalesOrderController'   => __DIR__ . '/src/Backend/Controller/SalesOrderController.php',
  'Backend\Controller\PurchaseOrderController'   => __DIR__ . '/src/Backend/Controller/PurchaseOrderController.php',
  'Backend\Controller\StockAdjustmentController'   => __DIR__ . '/src/Backend/Controller/StockAdjustmentController.php',
  'Backend\Controller\ReportsController'   => __DIR__ . '/src/Backend/Controller/ReportsController.php',
  'Backend\Controller\PaginatorTrait'   => __DIR__ . '/src/Backend/Controller/PaginatorTrait.php',
  'Backend\Controller\UserController'    => __DIR__ . '/src/Backend/Controller/UserController.php',
  'Backend\Model\Orders'                 => __DIR__ . '/src/Backend/Model/Orders.php',
  'Backend\Model\SalesOrders'                 => __DIR__ . '/src/Backend/Model/SalesOrders.php',
  'Backend\Model\PurchaseOrders'                 => __DIR__ . '/src/Backend/Model/PurchaseOrders.php',
  'Backend\Model\Projects'                 => __DIR__ . '/src/Backend/Model/Projects.php',
  'Backend\Model\Sequence'                 => __DIR__ . '/src/Backend/Model/Sequence.php',
  'Backend\Model\ProductVariants'        => __DIR__ . '/src/Backend/Model/ProductVariants.php',
  'Backend\Model\Products'               => __DIR__ . '/src/Backend/Model/Products.php',
  'Backend\Model\Users'               => __DIR__ . '/src/Backend/Model/Users.php',
  'Backend\Model\StockAdjustments'               => __DIR__ . '/src/Backend/Model/StockAdjustments.php',
);
