<?php
  $homeUrl = $this->url('home',array(),array('force_canonical' => true));
?>
<div class="box box-default no-print hideOnPrint">

    <div class="box-body">

        <div class="row">
          <div class="col-md-12">

            <?php if(count($validationMessages) > 0):?>

                 <div class="alert alert-warning alert-dismissable">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                    <h4><i class="icon fa fa-warning"></i> Alert!</h4>
                    <ul>
                    <?php foreach($validationMessages as $message):?>

                        <li>
                            <?php echo $message;?>
                        </li>


                    <?php endforeach?>
                    </ul>
                </div>

            <?php endif?>
            <?php if($success):?>

                 <div class="alert alert-success alert-dismissable">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                    <h4><i class="icon fa fa-success"></i> Success!</h4>
                    Successfully changed password.
                </div>

            <?php endif?>

            <form method="POST" action="<?php echo $homeUrl?>user/changepassword">
                <div class="col-sm-4">
                        <div class="form-group">
                          <label for="password">Password:</label>
                          <input type="password" class="form-control" id="password" name="password" placeholder="Password" value="<?php echo $formData['password']; ?>">
                        </div>
                </div>
                <div class="col-sm-4">
                        <div class="form-group">
                          <label for="password2">Confirm Password:</label>
                          <input type="password" class="form-control" id="password2" name="password2" placeholder="Confirm Password" value="<?php echo $formData['password2']; ?>">
                        </div>
                </div>

                <div class="col-sm-4">

                    <div class="form-group">
                      <label>&nbsp;</label>
                        <div class="input-group">
                          <button type="submit" id="add-variant-btn" class="btn btn-primary">Change Password</button>
                        </div>
                    </div>
                    </div>


            </form>
        </div>
        </div>
    </div>
</div>