<?php

$homeUrl = $this->url('home',array(),array('force_canonical' => true));

    function showBoolHTML($boolValue){
        if($boolValue){
            return '<small class="badge bg-green">Yes</small>';
        }
        return '<small class="badge bg-gray">No</small>';
    }

    function determineSortByLink($getParam, $sortName){

        if(isset($getParam['sort']) && $getParam['sort'] == $sortName){
            if(isset($getParam['order']) && $getParam['order'] == 'DESC'){
                $getParam['order'] = 'ASC';
            }else{
                $getParam['order'] = 'DESC';
            }
        }else{
            $getParam['sort'] = $sortName;
        }

        return http_build_query($getParam);
    }

    function generatePagination($getParam, $pagination, $homeUrl, $totalCount = 0)
    {
       
        $html = '<div class="row"><div class="col-sm-12">
                <div class="btn-group pull-right"> ['. number_format($totalCount) .' Results]   ';
        $homeUrl .= "/list";


        $currentPage = 1;
        if(isset($getParam['page']) && $getParam['page'] > 0){
            $currentPage = $getParam['page'];
        }
        $maxCount = count($pagination);

        $tmpGet = $getParam;
        foreach ($pagination as $key => $page) {
            if($page == 0 ) continue;
            $getParam['page'] = $page;
            $getQuery = http_build_query($getParam);

            $class = "btn-default";
            if($currentPage == $page)
                $class = "btn-primary";
            $html .= "<a style='padding-right:3px' href='{$homeUrl}?{$getQuery}'>";
            $html .= "<button class='btn {$class} btn-sm'>{$page}</button></a>";
        }
        $html .= '</div><!-- /.btn-group --></div></div>';
        return $html;
    }

    echo generatePagination($getParam, $pagination, $this->url(), $totalCount);

?>


<div class="box box-default">

<div class="box-body">



    <div class="row">



        <div class="col-sm-6">
            <a class="pull-left" href="<?php $this->url()?>add"> <button type="button" id="add-variant-btn" class="btn btn-primary btn-sm">Add</button> </a>
        </div>
        <div class="col-sm-6">
        <form action="<?php $this->url()?>list" method="GET">
            <div class="input-group">

                <input type="text" name="q" class="form-control input-sm pull-right" style="width: 150px;" placeholder="Search"
                  value="<?php if(isset($getParam['q'])) echo htmlspecialchars($getParam['q']);?>">
                <div class="input-group-btn">
                    <button type="submit" class="btn btn-sm btn-default"><i class="fa fa-search"></i></button>
                </div>
            </div>
            </form>
        </div>
    </div>



    <div class="row">


            <div class="box-body table-responsive col-sm-12">
                <table class="table table-hover table-striped table-bordered">
                    <tbody>
                    <tr>
                    <?php foreach($columnList as $columnName => $columnType):?>
                        <th>
                            <a href="<?php $this->url()?>list?<?php echo determineSortByLink($getParam, $columnName);?>">
                                <?php echo $columnName?>
                            </a>
                        </th>
                    <?php endforeach;?>
                        <th>
                            Action
                        </th>
                    </tr>
                    <?php 
                    if(count($data) > 0 ):
                        foreach($data as $row): ?>
                    <tr>
                        
                        <?php foreach($columnList as $columnName => $columnType):?>
                            <td>
                                <?php 
                                switch($columnType)
                                {

                                    case 'bool': 
                                            echo showBoolHTML($row[$columnName]); 
                                            break;
                                    case 'int': 
                                            echo number_format($row[$columnName]); 
                                            break;
                                    case 'date': 
                                            echo date('M d, Y', strtotime($row[$columnName])); 
                                            break;
                                    case 'datetime': 
                                            echo date('M d, Y H-i:s', strtotime($row[$columnName])); 
                                            break;
                                    default:
                                    case 'string': 
                                            echo htmlentities($row[$columnName]); 
                                            break;

                                }?>
                 

                                
                            </td>
                        <?php endforeach?>
                        <td id="accordion-option-<?php echo $row[$columnId]?>">
                        
                            <a href="<?php $this->url()?>details?id=<?php echo $row[$columnId]?>">
                                <button class="btn btn-primary btn-xs">
                                    Details
                                </button>
                            </a>
                            <a style="padding-left:2em" data-toggle="collapse" data-parent="#accordion-option-<?php echo $row[$columnId]?>"
                            href="#accordion-<?php echo $row[$columnId]?>">
                                <button class="btn btn-danger btn-xs">
                                Delete
                                </button>
                            </a>
                            <div id="accordion-<?php echo $row[$columnId]?>" class="collapse" style="height:0px">
                                <div class="box-body">
                                <a href="<?php $this->url()?>delete?id=">
                                    <button class="btn btn-danger btn-xs">
                                    Confirm Delete
                                    </button>
                                </a>
                                <a data-toggle="collapse" data-parent="#accordion-option-<?php echo $row[$columnId]?>"
                                   href="#accordion-<?php echo $row[$columnId]?>">
                                    <button class="btn btn-xs">Cancel</button>
                                </a>
                                </div>
                            </div>
                        </td>
                    </tr>
                   <?php endforeach; endif;?>
                </tbody></table>
            </div>

           

        </div>

 <?php echo generatePagination($getParam, $pagination, $homeUrl, $totalCount);?>

</div><!-- /.box-body -->
</div>
