<?php

$homeUrl = $this->url('home',array(),array('force_canonical' => true));
function determineSortByLink($getParam, $sortName){

    if(isset($getParam['sort']) && $getParam['sort'] == $sortName){
        if(isset($getParam['order']) && $getParam['order'] == 'DESC'){
            $getParam['order'] = 'ASC';
        }else{
            $getParam['order'] = 'DESC';
        }
    }else{
        $getParam['sort'] = $sortName;
    }

    return http_build_query($getParam);
}


function generatePagination($getParam, $pagination, $homeUrl)
{
   
    $html = '<div class="row"><div class="col-sm-12">
            <div class="btn-group pull-right"> Pages: ';
    $homeUrl .= "stockadjustment/list";

    $currentPage = 1;
    if(isset($getParam['page']) && $getParam['page'] > 0){
        $currentPage = $getParam['page'];
    }
    $maxCount = count($pagination);
    $tmpGet = $getParam;
    foreach ($pagination as $key => $page) {
        if($page == 0 ) continue;
        $getParam['page'] = $page;
        $getQuery = http_build_query($getParam);

        $class = "btn-default";
        if($currentPage == $page)
            $class = "btn-primary";
        $html .= "<a style='padding-right:3px' href='{$homeUrl}?{$getQuery}'>";
        $html .= "<button class='btn {$class} btn-sm'>{$page}</button></a>";
    }
    $html .= '</div><!-- /.btn-group --></div></div>';
    return $html;
}
    
    
?>
<div class="box box-default">

<div class="box-body">



    <div class="row">



        <div class="col-sm-6">
            <a class="pull-left" href="<?php echo $this->basePath();?>/stockadjustment/new"> <button type="button" id="add-variant-btn" class="btn btn-primary btn-sm">New Stock Adjustment</button> </a>
        </div>
        <div class="col-sm-6">
        <form action="<?php echo $this->basePath();?>/stockadjustment/list" method="GET">
            <div class="input-group">

                <input type="text" name="q" class="form-control input-sm pull-right" style="width: 150px;" placeholder="Search"
                  value="<?php if(isset($getParam['q'])) echo htmlspecialchars($getParam['q']);?>">
                <div class="input-group-btn">
                    <button type="submit" class="btn btn-sm btn-default"><i class="fa fa-search"></i></button>
                </div>
            </div>
            </form>
        </div>
    </div>



    <div class="row">


            <div class="box-body table-responsive col-sm-12">
                <table class="table table-hover table-striped table-bordered">
                    <tbody><tr>
                        <th>
                            <a href="<?php echo $this->basePath();?>/stockadjustment/list?<?php echo determineSortByLink($getParam, '_id');?>">
                            ID (<?php echo count($data); echo (count($data) == 1)? " item": " items" ?>)</a>
                        </th>
                        <th>
                            <a href="<?php echo $this->basePath();?>/stockadjustment/list?<?php echo determineSortByLink($getParam, 'reason');?>">
                            Reason </a>
                        </th>
                        <th>
                            <a href="<?php echo $this->basePath();?>/stockadjustment/list?<?php echo determineSortByLink($getParam, 'total_units');?>">
                            Units Adjusted </a>
                        </th>
                        <th>
                            <a href="<?php echo $this->basePath();?>/stockadjustment/list?<?php echo determineSortByLink($getParam, 'date_adjusted');?>">
                            Date Adjusted
                        </th>
                        <th>
                        <a href="<?php echo $this->basePath();?>/stockadjustment/list?<?php echo determineSortByLink($getParam, 'created');?>">
                            Created
                        </th>
                    </tr>
                    <?php 
                    if(count($data) > 0 )
                    {
                        foreach($data as $invoice){ 


                            ?>
                    <tr>
                        <td>
                            <a href="<?php echo $this->basePath();?>/stockadjustment/details/<?php echo $invoice['_id']?>">
                                   #<?php if (isset($invoice['_id'])) { echo $invoice['_id']; }?>
                            </a>
                        </td>
                        <td>
                            <?php echo ucwords($invoice['reason']);?>
                        </td>
                        <td>
                            <span class="pull-right"><?php echo number_format($invoice['total_units']);?>
                            </span> 
                        </td>

                        <td>
                           <?php echo Date("M d, Y", $invoice['date_adjusted']->sec);?>
                        </td>
                        <td>
                           <?php echo Date("M d, Y", $invoice['created']->sec);?>
                        </td>
                    </tr>
                   <?php }}?>
                </tbody></table>
            </div>
            

        </div>

    <?php echo generatePagination($getParam, $pagination, $homeUrl);?>


</div><!-- /.box-body -->
</div>
